// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/device.dart';
import 'api/diagnostics.dart';
import 'api/error.dart';
import 'api/lan.dart';
import 'api/preview.dart';
import 'api/receiver.dart';
import 'api/sender.dart';
import 'api/simple.dart';
import 'api/transfer.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 999477617;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'wisp_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<SelectionPreview> crateApiPreviewAppendPaths({
    required List<String> existingPaths,
    required List<String> newPaths,
  });

  Future<void> crateApiSenderCancelActiveSendTransfer();

  Future<void> crateApiReceiverCancelReceiverTransfer();

  Future<void> crateApiDiagnosticsCreateFirewallRule();

  String crateApiSimpleCurrentEndpointId();

  Future<QrPairingInfoData> crateApiReceiverCurrentQrPairingInfo();

  Future<ReceiverRegistration?> crateApiReceiverCurrentReceiverRegistration();

  DecodedTicketData crateApiLanDecodeTicketInfo({required String ticket});

  Future<ReceiverRegistration> crateApiReceiverEnsureReceiverRegistration({
    String? serverUrl,
    required String deviceName,
  });

  Future<String?> crateApiDiagnosticsFirewallInboundWarning();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<SelectionPreview> crateApiPreviewInspectPaths({
    required List<String> paths,
  });

  String crateApiDeviceRandomDeviceName();

  Future<ReceiverRegistration> crateApiReceiverRegisterReceiver({
    String? serverUrl,
    required String deviceName,
  });

  Future<SelectionPreview> crateApiPreviewRemovePath({
    required List<String> existingPaths,
    required String removedPath,
  });

  Future<void> crateApiReceiverRespondToReceiverOffer({required bool accept});

  Stream<DiagnosticsCheckData> crateApiDiagnosticsRunConnectionTest({
    String? serverUrl,
    required String downloadRoot,
  });

  Future<List<NearbyReceiverInfo>> crateApiLanScanNearbyReceivers({
    required BigInt timeoutSecs,
  });

  void crateApiSimpleSetAppIdentity({required List<int> secretKeyBytes});

  Future<void> crateApiReceiverSetReceiverDiscoverable({required bool enabled});

  Stream<ReceiverTransferEvent> crateApiReceiverStartReceiverTransferListener({
    String? serverUrl,
    required String downloadRoot,
    required String deviceName,
    required String deviceType,
  });

  Stream<SendTransferEvent> crateApiSenderStartSendTransfer({
    required SendTransferRequest request,
  });

  Stream<ReceiverPairingState> crateApiReceiverWatchReceiverPairing({
    String? serverUrl,
    required String downloadRoot,
    required String deviceName,
    required String deviceType,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<SelectionPreview> crateApiPreviewAppendPaths({
    required List<String> existingPaths,
    required List<String> newPaths,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(existingPaths, serializer);
          sse_encode_list_String(newPaths, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_selection_preview,
          decodeErrorData: sse_decode_user_facing_error_data,
        ),
        constMeta: kCrateApiPreviewAppendPathsConstMeta,
        argValues: [existingPaths, newPaths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPreviewAppendPathsConstMeta => const TaskConstMeta(
    debugName: "append_paths",
    argNames: ["existingPaths", "newPaths"],
  );

  @override
  Future<void> crateApiSenderCancelActiveSendTransfer() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_user_facing_error_data,
        ),
        constMeta: kCrateApiSenderCancelActiveSendTransferConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSenderCancelActiveSendTransferConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_active_send_transfer",
        argNames: [],
      );

  @override
  Future<void> crateApiReceiverCancelReceiverTransfer() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_user_facing_error_data,
        ),
        constMeta: kCrateApiReceiverCancelReceiverTransferConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiverCancelReceiverTransferConstMeta =>
      const TaskConstMeta(debugName: "cancel_receiver_transfer", argNames: []);

  @override
  Future<void> crateApiDiagnosticsCreateFirewallRule() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDiagnosticsCreateFirewallRuleConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiagnosticsCreateFirewallRuleConstMeta =>
      const TaskConstMeta(debugName: "create_firewall_rule", argNames: []);

  @override
  String crateApiSimpleCurrentEndpointId() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCurrentEndpointIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCurrentEndpointIdConstMeta =>
      const TaskConstMeta(debugName: "current_endpoint_id", argNames: []);

  @override
  Future<QrPairingInfoData> crateApiReceiverCurrentQrPairingInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qr_pairing_info_data,
          decodeErrorData: sse_decode_user_facing_error_data,
        ),
        constMeta: kCrateApiReceiverCurrentQrPairingInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiverCurrentQrPairingInfoConstMeta =>
      const TaskConstMeta(debugName: "current_qr_pairing_info", argNames: []);

  @override
  Future<ReceiverRegistration?> crateApiReceiverCurrentReceiverRegistration() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_receiver_registration,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReceiverCurrentReceiverRegistrationConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiverCurrentReceiverRegistrationConstMeta =>
      const TaskConstMeta(
        debugName: "current_receiver_registration",
        argNames: [],
      );

  @override
  DecodedTicketData crateApiLanDecodeTicketInfo({required String ticket}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ticket, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_decoded_ticket_data,
          decodeErrorData: sse_decode_user_facing_error_data,
        ),
        constMeta: kCrateApiLanDecodeTicketInfoConstMeta,
        argValues: [ticket],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanDecodeTicketInfoConstMeta =>
      const TaskConstMeta(
        debugName: "decode_ticket_info",
        argNames: ["ticket"],
      );

  @override
  Future<ReceiverRegistration> crateApiReceiverEnsureReceiverRegistration({
    String? serverUrl,
    required String deviceName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(serverUrl, serializer);
          sse_encode_String(deviceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_receiver_registration,
          decodeErrorData: sse_decode_user_facing_error_data,
        ),
        constMeta: kCrateApiReceiverEnsureReceiverRegistrationConstMeta,
        argValues: [serverUrl, deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiverEnsureReceiverRegistrationConstMeta =>
      const TaskConstMeta(
        debugName: "ensure_receiver_registration",
        argNames: ["serverUrl", "deviceName"],
      );

  @override
  Future<String?> crateApiDiagnosticsFirewallInboundWarning() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDiagnosticsFirewallInboundWarningConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiagnosticsFirewallInboundWarningConstMeta =>
      const TaskConstMeta(debugName: "firewall_inbound_warning", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<SelectionPreview> crateApiPreviewInspectPaths({
    required List<String> paths,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(paths, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_selection_preview,
          decodeErrorData: sse_decode_user_facing_error_data,
        ),
        constMeta: kCrateApiPreviewInspectPathsConstMeta,
        argValues: [paths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPreviewInspectPathsConstMeta =>
      const TaskConstMeta(debugName: "inspect_paths", argNames: ["paths"]);

  @override
  String crateApiDeviceRandomDeviceName() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDeviceRandomDeviceNameConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceRandomDeviceNameConstMeta =>
      const TaskConstMeta(debugName: "random_device_name", argNames: []);

  @override
  Future<ReceiverRegistration> crateApiReceiverRegisterReceiver({
    String? serverUrl,
    required String deviceName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(serverUrl, serializer);
          sse_encode_String(deviceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_receiver_registration,
          decodeErrorData: sse_decode_user_facing_error_data,
        ),
        constMeta: kCrateApiReceiverRegisterReceiverConstMeta,
        argValues: [serverUrl, deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiverRegisterReceiverConstMeta =>
      const TaskConstMeta(
        debugName: "register_receiver",
        argNames: ["serverUrl", "deviceName"],
      );

  @override
  Future<SelectionPreview> crateApiPreviewRemovePath({
    required List<String> existingPaths,
    required String removedPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(existingPaths, serializer);
          sse_encode_String(removedPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_selection_preview,
          decodeErrorData: sse_decode_user_facing_error_data,
        ),
        constMeta: kCrateApiPreviewRemovePathConstMeta,
        argValues: [existingPaths, removedPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPreviewRemovePathConstMeta => const TaskConstMeta(
    debugName: "remove_path",
    argNames: ["existingPaths", "removedPath"],
  );

  @override
  Future<void> crateApiReceiverRespondToReceiverOffer({required bool accept}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(accept, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_user_facing_error_data,
        ),
        constMeta: kCrateApiReceiverRespondToReceiverOfferConstMeta,
        argValues: [accept],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiverRespondToReceiverOfferConstMeta =>
      const TaskConstMeta(
        debugName: "respond_to_receiver_offer",
        argNames: ["accept"],
      );

  @override
  Stream<DiagnosticsCheckData> crateApiDiagnosticsRunConnectionTest({
    String? serverUrl,
    required String downloadRoot,
  }) {
    final sink = RustStreamSink<DiagnosticsCheckData>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_opt_String(serverUrl, serializer);
            sse_encode_String(downloadRoot, serializer);
            sse_encode_StreamSink_diagnostics_check_data_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 18,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiDiagnosticsRunConnectionTestConstMeta,
          argValues: [serverUrl, downloadRoot, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDiagnosticsRunConnectionTestConstMeta =>
      const TaskConstMeta(
        debugName: "run_connection_test",
        argNames: ["serverUrl", "downloadRoot", "sink"],
      );

  @override
  Future<List<NearbyReceiverInfo>> crateApiLanScanNearbyReceivers({
    required BigInt timeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(timeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_nearby_receiver_info,
          decodeErrorData: sse_decode_user_facing_error_data,
        ),
        constMeta: kCrateApiLanScanNearbyReceiversConstMeta,
        argValues: [timeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanScanNearbyReceiversConstMeta =>
      const TaskConstMeta(
        debugName: "scan_nearby_receivers",
        argNames: ["timeoutSecs"],
      );

  @override
  void crateApiSimpleSetAppIdentity({required List<int> secretKeyBytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(secretKeyBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSetAppIdentityConstMeta,
        argValues: [secretKeyBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSetAppIdentityConstMeta =>
      const TaskConstMeta(
        debugName: "set_app_identity",
        argNames: ["secretKeyBytes"],
      );

  @override
  Future<void> crateApiReceiverSetReceiverDiscoverable({
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_user_facing_error_data,
        ),
        constMeta: kCrateApiReceiverSetReceiverDiscoverableConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiverSetReceiverDiscoverableConstMeta =>
      const TaskConstMeta(
        debugName: "set_receiver_discoverable",
        argNames: ["enabled"],
      );

  @override
  Stream<ReceiverTransferEvent> crateApiReceiverStartReceiverTransferListener({
    String? serverUrl,
    required String downloadRoot,
    required String deviceName,
    required String deviceType,
  }) {
    final updates = RustStreamSink<ReceiverTransferEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_opt_String(serverUrl, serializer);
            sse_encode_String(downloadRoot, serializer);
            sse_encode_String(deviceName, serializer);
            sse_encode_String(deviceType, serializer);
            sse_encode_StreamSink_receiver_transfer_event_Sse(
              updates,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 22,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_user_facing_error_data,
          ),
          constMeta: kCrateApiReceiverStartReceiverTransferListenerConstMeta,
          argValues: [serverUrl, downloadRoot, deviceName, deviceType, updates],
          apiImpl: this,
        ),
      ),
    );
    return updates.stream;
  }

  TaskConstMeta get kCrateApiReceiverStartReceiverTransferListenerConstMeta =>
      const TaskConstMeta(
        debugName: "start_receiver_transfer_listener",
        argNames: [
          "serverUrl",
          "downloadRoot",
          "deviceName",
          "deviceType",
          "updates",
        ],
      );

  @override
  Stream<SendTransferEvent> crateApiSenderStartSendTransfer({
    required SendTransferRequest request,
  }) {
    final updates = RustStreamSink<SendTransferEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_send_transfer_request(request, serializer);
            sse_encode_StreamSink_send_transfer_event_Sse(updates, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 23,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_user_facing_error_data,
          ),
          constMeta: kCrateApiSenderStartSendTransferConstMeta,
          argValues: [request, updates],
          apiImpl: this,
        ),
      ),
    );
    return updates.stream;
  }

  TaskConstMeta get kCrateApiSenderStartSendTransferConstMeta =>
      const TaskConstMeta(
        debugName: "start_send_transfer",
        argNames: ["request", "updates"],
      );

  @override
  Stream<ReceiverPairingState> crateApiReceiverWatchReceiverPairing({
    String? serverUrl,
    required String downloadRoot,
    required String deviceName,
    required String deviceType,
  }) {
    final updates = RustStreamSink<ReceiverPairingState>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_opt_String(serverUrl, serializer);
            sse_encode_String(downloadRoot, serializer);
            sse_encode_String(deviceName, serializer);
            sse_encode_String(deviceType, serializer);
            sse_encode_StreamSink_receiver_pairing_state_Sse(
              updates,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 24,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_user_facing_error_data,
          ),
          constMeta: kCrateApiReceiverWatchReceiverPairingConstMeta,
          argValues: [serverUrl, downloadRoot, deviceName, deviceType, updates],
          apiImpl: this,
        ),
      ),
    );
    return updates.stream;
  }

  TaskConstMeta get kCrateApiReceiverWatchReceiverPairingConstMeta =>
      const TaskConstMeta(
        debugName: "watch_receiver_pairing",
        argNames: [
          "serverUrl",
          "downloadRoot",
          "deviceName",
          "deviceType",
          "updates",
        ],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<DiagnosticsCheckData>
  dco_decode_StreamSink_diagnostics_check_data_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<ReceiverPairingState>
  dco_decode_StreamSink_receiver_pairing_state_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<ReceiverTransferEvent>
  dco_decode_StreamSink_receiver_transfer_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<SendTransferEvent>
  dco_decode_StreamSink_send_transfer_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DiagnosticsActionData dco_decode_box_autoadd_diagnostics_action_data(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_diagnostics_action_data(raw);
  }

  @protected
  ReceiverConnectionPath dco_decode_box_autoadd_receiver_connection_path(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_receiver_connection_path(raw);
  }

  @protected
  ReceiverRegistration dco_decode_box_autoadd_receiver_registration(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_receiver_registration(raw);
  }

  @protected
  SendConnectionPath dco_decode_box_autoadd_send_connection_path(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_send_connection_path(raw);
  }

  @protected
  SendTransferRequest dco_decode_box_autoadd_send_transfer_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_send_transfer_request(raw);
  }

  @protected
  TransferPlanData dco_decode_box_autoadd_transfer_plan_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_transfer_plan_data(raw);
  }

  @protected
  TransferSnapshotData dco_decode_box_autoadd_transfer_snapshot_data(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_transfer_snapshot_data(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  UserFacingErrorData dco_decode_box_autoadd_user_facing_error_data(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_user_facing_error_data(raw);
  }

  @protected
  DecodedTicketData dco_decode_decoded_ticket_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DecodedTicketData(
      endpointId: dco_decode_String(arr[0]),
      deviceName: dco_decode_String(arr[1]),
      deviceType: dco_decode_String(arr[2]),
    );
  }

  @protected
  DiagnosticsActionData dco_decode_diagnostics_action_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DiagnosticsActionData(
      label: dco_decode_String(arr[0]),
      kind: dco_decode_diagnostics_action_kind(arr[1]),
      target: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  DiagnosticsActionKind dco_decode_diagnostics_action_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DiagnosticsActionKind.values[raw as int];
  }

  @protected
  DiagnosticsCheckData dco_decode_diagnostics_check_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return DiagnosticsCheckData(
      id: dco_decode_String(arr[0]),
      group: dco_decode_diagnostics_check_group(arr[1]),
      status: dco_decode_diagnostics_check_status(arr[2]),
      label: dco_decode_String(arr[3]),
      detail: dco_decode_String(arr[4]),
      hint: dco_decode_opt_String(arr[5]),
      action: dco_decode_opt_box_autoadd_diagnostics_action_data(arr[6]),
    );
  }

  @protected
  DiagnosticsCheckGroup dco_decode_diagnostics_check_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DiagnosticsCheckGroup.values[raw as int];
  }

  @protected
  DiagnosticsCheckStatus dco_decode_diagnostics_check_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DiagnosticsCheckStatus.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<NearbyReceiverInfo> dco_decode_list_nearby_receiver_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_nearby_receiver_info).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ReceiverTransferFile> dco_decode_list_receiver_transfer_file(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_receiver_transfer_file)
        .toList();
  }

  @protected
  List<SelectionItem> dco_decode_list_selection_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_selection_item).toList();
  }

  @protected
  List<TransferPlanFileData> dco_decode_list_transfer_plan_file_data(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_transfer_plan_file_data)
        .toList();
  }

  @protected
  NearbyReceiverInfo dco_decode_nearby_receiver_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return NearbyReceiverInfo(
      fullname: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      deviceType: dco_decode_String(arr[2]),
      code: dco_decode_String(arr[3]),
      ticket: dco_decode_String(arr[4]),
      endpointId: dco_decode_String(arr[5]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DiagnosticsActionData? dco_decode_opt_box_autoadd_diagnostics_action_data(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_diagnostics_action_data(raw);
  }

  @protected
  ReceiverConnectionPath? dco_decode_opt_box_autoadd_receiver_connection_path(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_receiver_connection_path(raw);
  }

  @protected
  ReceiverRegistration? dco_decode_opt_box_autoadd_receiver_registration(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_receiver_registration(raw);
  }

  @protected
  SendConnectionPath? dco_decode_opt_box_autoadd_send_connection_path(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_send_connection_path(raw);
  }

  @protected
  TransferPlanData? dco_decode_opt_box_autoadd_transfer_plan_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_transfer_plan_data(raw);
  }

  @protected
  TransferSnapshotData? dco_decode_opt_box_autoadd_transfer_snapshot_data(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_transfer_snapshot_data(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  UserFacingErrorData? dco_decode_opt_box_autoadd_user_facing_error_data(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_user_facing_error_data(raw);
  }

  @protected
  QrPairingInfoData dco_decode_qr_pairing_info_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return QrPairingInfoData(
      ticket: dco_decode_String(arr[0]),
      lanIps: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  ReceiverConnectionPath dco_decode_receiver_connection_path(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ReceiverConnectionPath(
      kind: dco_decode_String(arr[0]),
      relayUrl: dco_decode_opt_String(arr[1]),
      directAddr: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  ReceiverPairingState dco_decode_receiver_pairing_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ReceiverPairingState(
      code: dco_decode_opt_String(arr[0]),
      expiresAt: dco_decode_opt_String(arr[1]),
      stale: dco_decode_bool(arr[2]),
    );
  }

  @protected
  ReceiverRegistration dco_decode_receiver_registration(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ReceiverRegistration(
      code: dco_decode_String(arr[0]),
      expiresAt: dco_decode_String(arr[1]),
    );
  }

  @protected
  ReceiverTransferEvent dco_decode_receiver_transfer_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 17)
      throw Exception('unexpected arr length: expect 17 but see ${arr.length}');
    return ReceiverTransferEvent(
      phase: dco_decode_receiver_transfer_phase(arr[0]),
      senderName: dco_decode_String(arr[1]),
      senderDeviceType: dco_decode_String(arr[2]),
      destinationLabel: dco_decode_String(arr[3]),
      saveRootLabel: dco_decode_String(arr[4]),
      statusMessage: dco_decode_String(arr[5]),
      itemCount: dco_decode_u_64(arr[6]),
      totalSizeBytes: dco_decode_u_64(arr[7]),
      bytesReceived: dco_decode_u_64(arr[8]),
      plan: dco_decode_opt_box_autoadd_transfer_plan_data(arr[9]),
      snapshot: dco_decode_opt_box_autoadd_transfer_snapshot_data(arr[10]),
      totalSizeLabel: dco_decode_String(arr[11]),
      files: dco_decode_list_receiver_transfer_file(arr[12]),
      connectionPath: dco_decode_opt_box_autoadd_receiver_connection_path(
        arr[13],
      ),
      senderEndpointId: dco_decode_opt_String(arr[14]),
      senderTicket: dco_decode_opt_String(arr[15]),
      error: dco_decode_opt_box_autoadd_user_facing_error_data(arr[16]),
    );
  }

  @protected
  ReceiverTransferFile dco_decode_receiver_transfer_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ReceiverTransferFile(
      path: dco_decode_String(arr[0]),
      size: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  ReceiverTransferPhase dco_decode_receiver_transfer_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReceiverTransferPhase.values[raw as int];
  }

  @protected
  SelectionItem dco_decode_selection_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SelectionItem(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      isDirectory: dco_decode_bool(arr[2]),
      fileCount: dco_decode_u_64(arr[3]),
      totalSize: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  SelectionPreview dco_decode_selection_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SelectionPreview(
      items: dco_decode_list_selection_item(arr[0]),
      fileCount: dco_decode_u_64(arr[1]),
      totalSize: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  SendConnectionPath dco_decode_send_connection_path(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SendConnectionPath(
      kind: dco_decode_String(arr[0]),
      relayUrl: dco_decode_opt_String(arr[1]),
      directAddr: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  SendTransferEvent dco_decode_send_transfer_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return SendTransferEvent(
      phase: dco_decode_send_transfer_phase(arr[0]),
      destinationLabel: dco_decode_String(arr[1]),
      statusMessage: dco_decode_String(arr[2]),
      itemCount: dco_decode_u_64(arr[3]),
      totalSize: dco_decode_u_64(arr[4]),
      bytesSent: dco_decode_u_64(arr[5]),
      plan: dco_decode_opt_box_autoadd_transfer_plan_data(arr[6]),
      snapshot: dco_decode_opt_box_autoadd_transfer_snapshot_data(arr[7]),
      remoteDeviceType: dco_decode_opt_String(arr[8]),
      remoteEndpointId: dco_decode_opt_String(arr[9]),
      remoteTicket: dco_decode_opt_String(arr[10]),
      connectionPath: dco_decode_opt_box_autoadd_send_connection_path(arr[11]),
      error: dco_decode_opt_box_autoadd_user_facing_error_data(arr[12]),
    );
  }

  @protected
  SendTransferPhase dco_decode_send_transfer_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SendTransferPhase.values[raw as int];
  }

  @protected
  SendTransferRequest dco_decode_send_transfer_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SendTransferRequest(
      code: dco_decode_String(arr[0]),
      paths: dco_decode_list_String(arr[1]),
      serverUrl: dco_decode_opt_String(arr[2]),
      deviceName: dco_decode_String(arr[3]),
      deviceType: dco_decode_String(arr[4]),
      ticket: dco_decode_opt_String(arr[5]),
      lanDestinationLabel: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  TransferPhaseData dco_decode_transfer_phase_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TransferPhaseData.values[raw as int];
  }

  @protected
  TransferPlanData dco_decode_transfer_plan_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TransferPlanData(
      sessionId: dco_decode_String(arr[0]),
      totalFiles: dco_decode_u_32(arr[1]),
      totalBytes: dco_decode_u_64(arr[2]),
      files: dco_decode_list_transfer_plan_file_data(arr[3]),
    );
  }

  @protected
  TransferPlanFileData dco_decode_transfer_plan_file_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TransferPlanFileData(
      id: dco_decode_u_32(arr[0]),
      path: dco_decode_String(arr[1]),
      size: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  TransferSnapshotData dco_decode_transfer_snapshot_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return TransferSnapshotData(
      sessionId: dco_decode_String(arr[0]),
      phase: dco_decode_transfer_phase_data(arr[1]),
      totalFiles: dco_decode_u_32(arr[2]),
      completedFiles: dco_decode_u_32(arr[3]),
      totalBytes: dco_decode_u_64(arr[4]),
      bytesTransferred: dco_decode_u_64(arr[5]),
      activeFileId: dco_decode_opt_box_autoadd_u_32(arr[6]),
      activeFileBytes: dco_decode_opt_box_autoadd_u_64(arr[7]),
      bytesPerSec: dco_decode_opt_box_autoadd_u_64(arr[8]),
      etaSeconds: dco_decode_opt_box_autoadd_u_64(arr[9]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UserFacingErrorData dco_decode_user_facing_error_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return UserFacingErrorData(
      kind: dco_decode_user_facing_error_kind_data(arr[0]),
      title: dco_decode_String(arr[1]),
      message: dco_decode_String(arr[2]),
      recovery: dco_decode_opt_String(arr[3]),
      retryable: dco_decode_bool(arr[4]),
    );
  }

  @protected
  UserFacingErrorKindData dco_decode_user_facing_error_kind_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UserFacingErrorKindData.values[raw as int];
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<DiagnosticsCheckData>
  sse_decode_StreamSink_diagnostics_check_data_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<ReceiverPairingState>
  sse_decode_StreamSink_receiver_pairing_state_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<ReceiverTransferEvent>
  sse_decode_StreamSink_receiver_transfer_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<SendTransferEvent>
  sse_decode_StreamSink_send_transfer_event_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DiagnosticsActionData sse_decode_box_autoadd_diagnostics_action_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_diagnostics_action_data(deserializer));
  }

  @protected
  ReceiverConnectionPath sse_decode_box_autoadd_receiver_connection_path(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_receiver_connection_path(deserializer));
  }

  @protected
  ReceiverRegistration sse_decode_box_autoadd_receiver_registration(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_receiver_registration(deserializer));
  }

  @protected
  SendConnectionPath sse_decode_box_autoadd_send_connection_path(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_send_connection_path(deserializer));
  }

  @protected
  SendTransferRequest sse_decode_box_autoadd_send_transfer_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_send_transfer_request(deserializer));
  }

  @protected
  TransferPlanData sse_decode_box_autoadd_transfer_plan_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_transfer_plan_data(deserializer));
  }

  @protected
  TransferSnapshotData sse_decode_box_autoadd_transfer_snapshot_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_transfer_snapshot_data(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  UserFacingErrorData sse_decode_box_autoadd_user_facing_error_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_user_facing_error_data(deserializer));
  }

  @protected
  DecodedTicketData sse_decode_decoded_ticket_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_endpointId = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_deviceType = sse_decode_String(deserializer);
    return DecodedTicketData(
      endpointId: var_endpointId,
      deviceName: var_deviceName,
      deviceType: var_deviceType,
    );
  }

  @protected
  DiagnosticsActionData sse_decode_diagnostics_action_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_label = sse_decode_String(deserializer);
    var var_kind = sse_decode_diagnostics_action_kind(deserializer);
    var var_target = sse_decode_opt_String(deserializer);
    return DiagnosticsActionData(
      label: var_label,
      kind: var_kind,
      target: var_target,
    );
  }

  @protected
  DiagnosticsActionKind sse_decode_diagnostics_action_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DiagnosticsActionKind.values[inner];
  }

  @protected
  DiagnosticsCheckData sse_decode_diagnostics_check_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_group = sse_decode_diagnostics_check_group(deserializer);
    var var_status = sse_decode_diagnostics_check_status(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_detail = sse_decode_String(deserializer);
    var var_hint = sse_decode_opt_String(deserializer);
    var var_action = sse_decode_opt_box_autoadd_diagnostics_action_data(
      deserializer,
    );
    return DiagnosticsCheckData(
      id: var_id,
      group: var_group,
      status: var_status,
      label: var_label,
      detail: var_detail,
      hint: var_hint,
      action: var_action,
    );
  }

  @protected
  DiagnosticsCheckGroup sse_decode_diagnostics_check_group(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DiagnosticsCheckGroup.values[inner];
  }

  @protected
  DiagnosticsCheckStatus sse_decode_diagnostics_check_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DiagnosticsCheckStatus.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<NearbyReceiverInfo> sse_decode_list_nearby_receiver_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NearbyReceiverInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_nearby_receiver_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ReceiverTransferFile> sse_decode_list_receiver_transfer_file(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ReceiverTransferFile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_receiver_transfer_file(deserializer));
    }
    return ans_;
  }

  @protected
  List<SelectionItem> sse_decode_list_selection_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SelectionItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_selection_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<TransferPlanFileData> sse_decode_list_transfer_plan_file_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TransferPlanFileData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_transfer_plan_file_data(deserializer));
    }
    return ans_;
  }

  @protected
  NearbyReceiverInfo sse_decode_nearby_receiver_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fullname = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_deviceType = sse_decode_String(deserializer);
    var var_code = sse_decode_String(deserializer);
    var var_ticket = sse_decode_String(deserializer);
    var var_endpointId = sse_decode_String(deserializer);
    return NearbyReceiverInfo(
      fullname: var_fullname,
      label: var_label,
      deviceType: var_deviceType,
      code: var_code,
      ticket: var_ticket,
      endpointId: var_endpointId,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DiagnosticsActionData? sse_decode_opt_box_autoadd_diagnostics_action_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_diagnostics_action_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReceiverConnectionPath? sse_decode_opt_box_autoadd_receiver_connection_path(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_receiver_connection_path(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReceiverRegistration? sse_decode_opt_box_autoadd_receiver_registration(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_receiver_registration(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SendConnectionPath? sse_decode_opt_box_autoadd_send_connection_path(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_send_connection_path(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TransferPlanData? sse_decode_opt_box_autoadd_transfer_plan_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_transfer_plan_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TransferSnapshotData? sse_decode_opt_box_autoadd_transfer_snapshot_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_transfer_snapshot_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  UserFacingErrorData? sse_decode_opt_box_autoadd_user_facing_error_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_user_facing_error_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QrPairingInfoData sse_decode_qr_pairing_info_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ticket = sse_decode_String(deserializer);
    var var_lanIps = sse_decode_list_String(deserializer);
    return QrPairingInfoData(ticket: var_ticket, lanIps: var_lanIps);
  }

  @protected
  ReceiverConnectionPath sse_decode_receiver_connection_path(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_relayUrl = sse_decode_opt_String(deserializer);
    var var_directAddr = sse_decode_opt_String(deserializer);
    return ReceiverConnectionPath(
      kind: var_kind,
      relayUrl: var_relayUrl,
      directAddr: var_directAddr,
    );
  }

  @protected
  ReceiverPairingState sse_decode_receiver_pairing_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_opt_String(deserializer);
    var var_expiresAt = sse_decode_opt_String(deserializer);
    var var_stale = sse_decode_bool(deserializer);
    return ReceiverPairingState(
      code: var_code,
      expiresAt: var_expiresAt,
      stale: var_stale,
    );
  }

  @protected
  ReceiverRegistration sse_decode_receiver_registration(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_expiresAt = sse_decode_String(deserializer);
    return ReceiverRegistration(code: var_code, expiresAt: var_expiresAt);
  }

  @protected
  ReceiverTransferEvent sse_decode_receiver_transfer_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_phase = sse_decode_receiver_transfer_phase(deserializer);
    var var_senderName = sse_decode_String(deserializer);
    var var_senderDeviceType = sse_decode_String(deserializer);
    var var_destinationLabel = sse_decode_String(deserializer);
    var var_saveRootLabel = sse_decode_String(deserializer);
    var var_statusMessage = sse_decode_String(deserializer);
    var var_itemCount = sse_decode_u_64(deserializer);
    var var_totalSizeBytes = sse_decode_u_64(deserializer);
    var var_bytesReceived = sse_decode_u_64(deserializer);
    var var_plan = sse_decode_opt_box_autoadd_transfer_plan_data(deserializer);
    var var_snapshot = sse_decode_opt_box_autoadd_transfer_snapshot_data(
      deserializer,
    );
    var var_totalSizeLabel = sse_decode_String(deserializer);
    var var_files = sse_decode_list_receiver_transfer_file(deserializer);
    var var_connectionPath =
        sse_decode_opt_box_autoadd_receiver_connection_path(deserializer);
    var var_senderEndpointId = sse_decode_opt_String(deserializer);
    var var_senderTicket = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_box_autoadd_user_facing_error_data(
      deserializer,
    );
    return ReceiverTransferEvent(
      phase: var_phase,
      senderName: var_senderName,
      senderDeviceType: var_senderDeviceType,
      destinationLabel: var_destinationLabel,
      saveRootLabel: var_saveRootLabel,
      statusMessage: var_statusMessage,
      itemCount: var_itemCount,
      totalSizeBytes: var_totalSizeBytes,
      bytesReceived: var_bytesReceived,
      plan: var_plan,
      snapshot: var_snapshot,
      totalSizeLabel: var_totalSizeLabel,
      files: var_files,
      connectionPath: var_connectionPath,
      senderEndpointId: var_senderEndpointId,
      senderTicket: var_senderTicket,
      error: var_error,
    );
  }

  @protected
  ReceiverTransferFile sse_decode_receiver_transfer_file(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    return ReceiverTransferFile(path: var_path, size: var_size);
  }

  @protected
  ReceiverTransferPhase sse_decode_receiver_transfer_phase(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ReceiverTransferPhase.values[inner];
  }

  @protected
  SelectionItem sse_decode_selection_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_isDirectory = sse_decode_bool(deserializer);
    var var_fileCount = sse_decode_u_64(deserializer);
    var var_totalSize = sse_decode_u_64(deserializer);
    return SelectionItem(
      name: var_name,
      path: var_path,
      isDirectory: var_isDirectory,
      fileCount: var_fileCount,
      totalSize: var_totalSize,
    );
  }

  @protected
  SelectionPreview sse_decode_selection_preview(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_selection_item(deserializer);
    var var_fileCount = sse_decode_u_64(deserializer);
    var var_totalSize = sse_decode_u_64(deserializer);
    return SelectionPreview(
      items: var_items,
      fileCount: var_fileCount,
      totalSize: var_totalSize,
    );
  }

  @protected
  SendConnectionPath sse_decode_send_connection_path(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_relayUrl = sse_decode_opt_String(deserializer);
    var var_directAddr = sse_decode_opt_String(deserializer);
    return SendConnectionPath(
      kind: var_kind,
      relayUrl: var_relayUrl,
      directAddr: var_directAddr,
    );
  }

  @protected
  SendTransferEvent sse_decode_send_transfer_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_phase = sse_decode_send_transfer_phase(deserializer);
    var var_destinationLabel = sse_decode_String(deserializer);
    var var_statusMessage = sse_decode_String(deserializer);
    var var_itemCount = sse_decode_u_64(deserializer);
    var var_totalSize = sse_decode_u_64(deserializer);
    var var_bytesSent = sse_decode_u_64(deserializer);
    var var_plan = sse_decode_opt_box_autoadd_transfer_plan_data(deserializer);
    var var_snapshot = sse_decode_opt_box_autoadd_transfer_snapshot_data(
      deserializer,
    );
    var var_remoteDeviceType = sse_decode_opt_String(deserializer);
    var var_remoteEndpointId = sse_decode_opt_String(deserializer);
    var var_remoteTicket = sse_decode_opt_String(deserializer);
    var var_connectionPath = sse_decode_opt_box_autoadd_send_connection_path(
      deserializer,
    );
    var var_error = sse_decode_opt_box_autoadd_user_facing_error_data(
      deserializer,
    );
    return SendTransferEvent(
      phase: var_phase,
      destinationLabel: var_destinationLabel,
      statusMessage: var_statusMessage,
      itemCount: var_itemCount,
      totalSize: var_totalSize,
      bytesSent: var_bytesSent,
      plan: var_plan,
      snapshot: var_snapshot,
      remoteDeviceType: var_remoteDeviceType,
      remoteEndpointId: var_remoteEndpointId,
      remoteTicket: var_remoteTicket,
      connectionPath: var_connectionPath,
      error: var_error,
    );
  }

  @protected
  SendTransferPhase sse_decode_send_transfer_phase(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SendTransferPhase.values[inner];
  }

  @protected
  SendTransferRequest sse_decode_send_transfer_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_paths = sse_decode_list_String(deserializer);
    var var_serverUrl = sse_decode_opt_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_deviceType = sse_decode_String(deserializer);
    var var_ticket = sse_decode_opt_String(deserializer);
    var var_lanDestinationLabel = sse_decode_opt_String(deserializer);
    return SendTransferRequest(
      code: var_code,
      paths: var_paths,
      serverUrl: var_serverUrl,
      deviceName: var_deviceName,
      deviceType: var_deviceType,
      ticket: var_ticket,
      lanDestinationLabel: var_lanDestinationLabel,
    );
  }

  @protected
  TransferPhaseData sse_decode_transfer_phase_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TransferPhaseData.values[inner];
  }

  @protected
  TransferPlanData sse_decode_transfer_plan_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_totalFiles = sse_decode_u_32(deserializer);
    var var_totalBytes = sse_decode_u_64(deserializer);
    var var_files = sse_decode_list_transfer_plan_file_data(deserializer);
    return TransferPlanData(
      sessionId: var_sessionId,
      totalFiles: var_totalFiles,
      totalBytes: var_totalBytes,
      files: var_files,
    );
  }

  @protected
  TransferPlanFileData sse_decode_transfer_plan_file_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    return TransferPlanFileData(id: var_id, path: var_path, size: var_size);
  }

  @protected
  TransferSnapshotData sse_decode_transfer_snapshot_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_phase = sse_decode_transfer_phase_data(deserializer);
    var var_totalFiles = sse_decode_u_32(deserializer);
    var var_completedFiles = sse_decode_u_32(deserializer);
    var var_totalBytes = sse_decode_u_64(deserializer);
    var var_bytesTransferred = sse_decode_u_64(deserializer);
    var var_activeFileId = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_activeFileBytes = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_bytesPerSec = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_etaSeconds = sse_decode_opt_box_autoadd_u_64(deserializer);
    return TransferSnapshotData(
      sessionId: var_sessionId,
      phase: var_phase,
      totalFiles: var_totalFiles,
      completedFiles: var_completedFiles,
      totalBytes: var_totalBytes,
      bytesTransferred: var_bytesTransferred,
      activeFileId: var_activeFileId,
      activeFileBytes: var_activeFileBytes,
      bytesPerSec: var_bytesPerSec,
      etaSeconds: var_etaSeconds,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UserFacingErrorData sse_decode_user_facing_error_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_user_facing_error_kind_data(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_recovery = sse_decode_opt_String(deserializer);
    var var_retryable = sse_decode_bool(deserializer);
    return UserFacingErrorData(
      kind: var_kind,
      title: var_title,
      message: var_message,
      recovery: var_recovery,
      retryable: var_retryable,
    );
  }

  @protected
  UserFacingErrorKindData sse_decode_user_facing_error_kind_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return UserFacingErrorKindData.values[inner];
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_diagnostics_check_data_Sse(
    RustStreamSink<DiagnosticsCheckData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_diagnostics_check_data,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_receiver_pairing_state_Sse(
    RustStreamSink<ReceiverPairingState> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_receiver_pairing_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_receiver_transfer_event_Sse(
    RustStreamSink<ReceiverTransferEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_receiver_transfer_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_send_transfer_event_Sse(
    RustStreamSink<SendTransferEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_send_transfer_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_diagnostics_action_data(
    DiagnosticsActionData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_diagnostics_action_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_receiver_connection_path(
    ReceiverConnectionPath self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_receiver_connection_path(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_receiver_registration(
    ReceiverRegistration self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_receiver_registration(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_send_connection_path(
    SendConnectionPath self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_send_connection_path(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_send_transfer_request(
    SendTransferRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_send_transfer_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_transfer_plan_data(
    TransferPlanData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transfer_plan_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_transfer_snapshot_data(
    TransferSnapshotData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transfer_snapshot_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_user_facing_error_data(
    UserFacingErrorData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_user_facing_error_data(self, serializer);
  }

  @protected
  void sse_encode_decoded_ticket_data(
    DecodedTicketData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.endpointId, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.deviceType, serializer);
  }

  @protected
  void sse_encode_diagnostics_action_data(
    DiagnosticsActionData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.label, serializer);
    sse_encode_diagnostics_action_kind(self.kind, serializer);
    sse_encode_opt_String(self.target, serializer);
  }

  @protected
  void sse_encode_diagnostics_action_kind(
    DiagnosticsActionKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_diagnostics_check_data(
    DiagnosticsCheckData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_diagnostics_check_group(self.group, serializer);
    sse_encode_diagnostics_check_status(self.status, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.detail, serializer);
    sse_encode_opt_String(self.hint, serializer);
    sse_encode_opt_box_autoadd_diagnostics_action_data(self.action, serializer);
  }

  @protected
  void sse_encode_diagnostics_check_group(
    DiagnosticsCheckGroup self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_diagnostics_check_status(
    DiagnosticsCheckStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_nearby_receiver_info(
    List<NearbyReceiverInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_nearby_receiver_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_receiver_transfer_file(
    List<ReceiverTransferFile> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_receiver_transfer_file(item, serializer);
    }
  }

  @protected
  void sse_encode_list_selection_item(
    List<SelectionItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_selection_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_transfer_plan_file_data(
    List<TransferPlanFileData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_transfer_plan_file_data(item, serializer);
    }
  }

  @protected
  void sse_encode_nearby_receiver_info(
    NearbyReceiverInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fullname, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.deviceType, serializer);
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.ticket, serializer);
    sse_encode_String(self.endpointId, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_diagnostics_action_data(
    DiagnosticsActionData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_diagnostics_action_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_receiver_connection_path(
    ReceiverConnectionPath? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_receiver_connection_path(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_receiver_registration(
    ReceiverRegistration? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_receiver_registration(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_send_connection_path(
    SendConnectionPath? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_send_connection_path(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_transfer_plan_data(
    TransferPlanData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_transfer_plan_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_transfer_snapshot_data(
    TransferSnapshotData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_transfer_snapshot_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_user_facing_error_data(
    UserFacingErrorData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_user_facing_error_data(self, serializer);
    }
  }

  @protected
  void sse_encode_qr_pairing_info_data(
    QrPairingInfoData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ticket, serializer);
    sse_encode_list_String(self.lanIps, serializer);
  }

  @protected
  void sse_encode_receiver_connection_path(
    ReceiverConnectionPath self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.relayUrl, serializer);
    sse_encode_opt_String(self.directAddr, serializer);
  }

  @protected
  void sse_encode_receiver_pairing_state(
    ReceiverPairingState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.code, serializer);
    sse_encode_opt_String(self.expiresAt, serializer);
    sse_encode_bool(self.stale, serializer);
  }

  @protected
  void sse_encode_receiver_registration(
    ReceiverRegistration self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.expiresAt, serializer);
  }

  @protected
  void sse_encode_receiver_transfer_event(
    ReceiverTransferEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_receiver_transfer_phase(self.phase, serializer);
    sse_encode_String(self.senderName, serializer);
    sse_encode_String(self.senderDeviceType, serializer);
    sse_encode_String(self.destinationLabel, serializer);
    sse_encode_String(self.saveRootLabel, serializer);
    sse_encode_String(self.statusMessage, serializer);
    sse_encode_u_64(self.itemCount, serializer);
    sse_encode_u_64(self.totalSizeBytes, serializer);
    sse_encode_u_64(self.bytesReceived, serializer);
    sse_encode_opt_box_autoadd_transfer_plan_data(self.plan, serializer);
    sse_encode_opt_box_autoadd_transfer_snapshot_data(
      self.snapshot,
      serializer,
    );
    sse_encode_String(self.totalSizeLabel, serializer);
    sse_encode_list_receiver_transfer_file(self.files, serializer);
    sse_encode_opt_box_autoadd_receiver_connection_path(
      self.connectionPath,
      serializer,
    );
    sse_encode_opt_String(self.senderEndpointId, serializer);
    sse_encode_opt_String(self.senderTicket, serializer);
    sse_encode_opt_box_autoadd_user_facing_error_data(self.error, serializer);
  }

  @protected
  void sse_encode_receiver_transfer_file(
    ReceiverTransferFile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_u_64(self.size, serializer);
  }

  @protected
  void sse_encode_receiver_transfer_phase(
    ReceiverTransferPhase self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_selection_item(SelectionItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.isDirectory, serializer);
    sse_encode_u_64(self.fileCount, serializer);
    sse_encode_u_64(self.totalSize, serializer);
  }

  @protected
  void sse_encode_selection_preview(
    SelectionPreview self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_selection_item(self.items, serializer);
    sse_encode_u_64(self.fileCount, serializer);
    sse_encode_u_64(self.totalSize, serializer);
  }

  @protected
  void sse_encode_send_connection_path(
    SendConnectionPath self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.relayUrl, serializer);
    sse_encode_opt_String(self.directAddr, serializer);
  }

  @protected
  void sse_encode_send_transfer_event(
    SendTransferEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_send_transfer_phase(self.phase, serializer);
    sse_encode_String(self.destinationLabel, serializer);
    sse_encode_String(self.statusMessage, serializer);
    sse_encode_u_64(self.itemCount, serializer);
    sse_encode_u_64(self.totalSize, serializer);
    sse_encode_u_64(self.bytesSent, serializer);
    sse_encode_opt_box_autoadd_transfer_plan_data(self.plan, serializer);
    sse_encode_opt_box_autoadd_transfer_snapshot_data(
      self.snapshot,
      serializer,
    );
    sse_encode_opt_String(self.remoteDeviceType, serializer);
    sse_encode_opt_String(self.remoteEndpointId, serializer);
    sse_encode_opt_String(self.remoteTicket, serializer);
    sse_encode_opt_box_autoadd_send_connection_path(
      self.connectionPath,
      serializer,
    );
    sse_encode_opt_box_autoadd_user_facing_error_data(self.error, serializer);
  }

  @protected
  void sse_encode_send_transfer_phase(
    SendTransferPhase self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_send_transfer_request(
    SendTransferRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_list_String(self.paths, serializer);
    sse_encode_opt_String(self.serverUrl, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.deviceType, serializer);
    sse_encode_opt_String(self.ticket, serializer);
    sse_encode_opt_String(self.lanDestinationLabel, serializer);
  }

  @protected
  void sse_encode_transfer_phase_data(
    TransferPhaseData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_transfer_plan_data(
    TransferPlanData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_u_32(self.totalFiles, serializer);
    sse_encode_u_64(self.totalBytes, serializer);
    sse_encode_list_transfer_plan_file_data(self.files, serializer);
  }

  @protected
  void sse_encode_transfer_plan_file_data(
    TransferPlanFileData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_u_64(self.size, serializer);
  }

  @protected
  void sse_encode_transfer_snapshot_data(
    TransferSnapshotData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_transfer_phase_data(self.phase, serializer);
    sse_encode_u_32(self.totalFiles, serializer);
    sse_encode_u_32(self.completedFiles, serializer);
    sse_encode_u_64(self.totalBytes, serializer);
    sse_encode_u_64(self.bytesTransferred, serializer);
    sse_encode_opt_box_autoadd_u_32(self.activeFileId, serializer);
    sse_encode_opt_box_autoadd_u_64(self.activeFileBytes, serializer);
    sse_encode_opt_box_autoadd_u_64(self.bytesPerSec, serializer);
    sse_encode_opt_box_autoadd_u_64(self.etaSeconds, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_user_facing_error_data(
    UserFacingErrorData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_user_facing_error_kind_data(self.kind, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_String(self.recovery, serializer);
    sse_encode_bool(self.retryable, serializer);
  }

  @protected
  void sse_encode_user_facing_error_kind_data(
    UserFacingErrorKindData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
