// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_action`, `map_check_result`, `map_group`, `map_status`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Runs the Rust-side connection-test checks and streams each result as
/// it resolves.  The stream closes when all checks have been emitted.
Stream<DiagnosticsCheckData> runConnectionTest({
  String? serverUrl,
  required String downloadRoot,
}) => RustLib.instance.api.crateApiDiagnosticsRunConnectionTest(
  serverUrl: serverUrl,
  downloadRoot: downloadRoot,
);

/// Creates a Windows Firewall inbound-Allow rule for the currently-running
/// executable.  Triggers a UAC prompt unless already elevated.  Returns the
/// error reason on failure (UAC denied, PowerShell missing, etc.) so the UI
/// can surface it in a snackbar.
Future<void> createFirewallRule() =>
    RustLib.instance.api.crateApiDiagnosticsCreateFirewallRule();

/// Lightweight probe used by the home-screen banner: returns a short reason
/// string when Windows Firewall is likely to block inbound transfers, or
/// `None` if the firewall is fine (or we're not on Windows).
Future<String?> firewallInboundWarning() =>
    RustLib.instance.api.crateApiDiagnosticsFirewallInboundWarning();

class DiagnosticsActionData {
  final String label;
  final DiagnosticsActionKind kind;
  final String? target;

  const DiagnosticsActionData({
    required this.label,
    required this.kind,
    this.target,
  });

  @override
  int get hashCode => label.hashCode ^ kind.hashCode ^ target.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosticsActionData &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          kind == other.kind &&
          target == other.target;
}

enum DiagnosticsActionKind {
  openAppSettings,
  openUrl,
  retry,
  createFirewallRule,
}

class DiagnosticsCheckData {
  final String id;
  final DiagnosticsCheckGroup group;
  final DiagnosticsCheckStatus status;
  final String label;
  final String detail;
  final String? hint;
  final DiagnosticsActionData? action;

  const DiagnosticsCheckData({
    required this.id,
    required this.group,
    required this.status,
    required this.label,
    required this.detail,
    this.hint,
    this.action,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      group.hashCode ^
      status.hashCode ^
      label.hashCode ^
      detail.hashCode ^
      hint.hashCode ^
      action.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosticsCheckData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          group == other.group &&
          status == other.status &&
          label == other.label &&
          detail == other.detail &&
          hint == other.hint &&
          action == other.action;
}

enum DiagnosticsCheckGroup { network, rendezvous, lan, p2P, permissions, local }

enum DiagnosticsCheckStatus { running, pass, warn, fail, skipped }
