// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_nearby_receiver`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<List<NearbyReceiverInfo>> scanNearbyReceivers({
  required BigInt timeoutSecs,
}) => RustLib.instance.api.crateApiLanScanNearbyReceivers(
  timeoutSecs: timeoutSecs,
);

/// Detect a likely USB-tethering link on a local interface (no network I/O).
/// Returns null when no USB-over-IP link is present.
UsbLinkData? detectUsbLink() => RustLib.instance.api.crateApiLanDetectUsbLink();

/// Pure decode (no network) of a ticket string. Used by the QR scanner so
/// the sender UI can show the receiver's name/type/pubkey before dialing.
DecodedTicketData decodeTicketInfo({required String ticket}) =>
    RustLib.instance.api.crateApiLanDecodeTicketInfo(ticket: ticket);

class DecodedTicketData {
  final String endpointId;
  final String deviceName;
  final String deviceType;

  const DecodedTicketData({
    required this.endpointId,
    required this.deviceName,
    required this.deviceType,
  });

  @override
  int get hashCode =>
      endpointId.hashCode ^ deviceName.hashCode ^ deviceType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedTicketData &&
          runtimeType == other.runtimeType &&
          endpointId == other.endpointId &&
          deviceName == other.deviceName &&
          deviceType == other.deviceType;
}

class NearbyReceiverInfo {
  final String fullname;
  final String label;
  final String deviceType;
  final String code;
  final String ticket;
  final String endpointId;

  const NearbyReceiverInfo({
    required this.fullname,
    required this.label,
    required this.deviceType,
    required this.code,
    required this.ticket,
    required this.endpointId,
  });

  @override
  int get hashCode =>
      fullname.hashCode ^
      label.hashCode ^
      deviceType.hashCode ^
      code.hashCode ^
      ticket.hashCode ^
      endpointId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NearbyReceiverInfo &&
          runtimeType == other.runtimeType &&
          fullname == other.fullname &&
          label == other.label &&
          deviceType == other.deviceType &&
          code == other.code &&
          ticket == other.ticket &&
          endpointId == other.endpointId;
}

/// Heuristic info about a detected USB-tethering (IP-over-USB) link, surfaced
/// to the Flutter UI so it can confirm a cable link is present and guide setup.
class UsbLinkData {
  final String localIp;

  /// True when this device is the tethering host (the phone).
  final bool isHost;

  /// The peer's gateway IP (the phone) when inferable, else null.
  final String? gatewayIp;

  const UsbLinkData({
    required this.localIp,
    required this.isHost,
    this.gatewayIp,
  });

  @override
  int get hashCode => localIp.hashCode ^ isHost.hashCode ^ gatewayIp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UsbLinkData &&
          runtimeType == other.runtimeType &&
          localIp == other.localIp &&
          isHost == other.isHost &&
          gatewayIp == other.gatewayIp;
}
