// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'transfer.dart';

// These functions are ignored because they are not marked as `pub`: `current_service_endpoint`, `current_service`, `ensure_receiver_service`, `existing_service_for_config`, `map_connection_path`, `map_event`, `map_file_row`, `map_pairing_state`, `map_phase`, `map_plan_file`, `map_plan`, `map_qr_pairing_info`, `map_registration`, `map_snapshot`, `pairing_registration`, `replace_pairing_task`, `replace_updates_task`, `sanitize_text_file_name`, `scan_nearby_with_receiver`, `set_discoverable`, `unique_text_path`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BridgeReceiverConfig`, `BridgeReceiverState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<ReceiverRegistration> registerReceiver({
  String? serverUrl,
  required String deviceName,
}) => RustLib.instance.api.crateApiReceiverRegisterReceiver(
  serverUrl: serverUrl,
  deviceName: deviceName,
);

Future<ReceiverRegistration> ensureReceiverRegistration({
  String? serverUrl,
  required String deviceName,
}) => RustLib.instance.api.crateApiReceiverEnsureReceiverRegistration(
  serverUrl: serverUrl,
  deviceName: deviceName,
);

Future<ReceiverRegistration?> currentReceiverRegistration() =>
    RustLib.instance.api.crateApiReceiverCurrentReceiverRegistration();

/// Returns a ticket plus the LAN-routable IPs of the local receiver.
/// The receiver service must already be running.  Designed for the QR
/// pairing screen — the ticket is built from currently-known addresses
/// without waiting on relay handshake, so it works on offline-LAN.
Future<QrPairingInfoData> currentQrPairingInfo() =>
    RustLib.instance.api.crateApiReceiverCurrentQrPairingInfo();

Stream<ReceiverPairingState> watchReceiverPairing({
  String? serverUrl,
  required String downloadRoot,
  required String deviceName,
  required String deviceType,
}) => RustLib.instance.api.crateApiReceiverWatchReceiverPairing(
  serverUrl: serverUrl,
  downloadRoot: downloadRoot,
  deviceName: deviceName,
  deviceType: deviceType,
);

Future<void> setReceiverDiscoverable({required bool enabled}) => RustLib
    .instance
    .api
    .crateApiReceiverSetReceiverDiscoverable(enabled: enabled);

Stream<ReceiverTransferEvent> startReceiverTransferListener({
  String? serverUrl,
  required String downloadRoot,
  required String deviceName,
  required String deviceType,
}) => RustLib.instance.api.crateApiReceiverStartReceiverTransferListener(
  serverUrl: serverUrl,
  downloadRoot: downloadRoot,
  deviceName: deviceName,
  deviceType: deviceType,
);

Future<void> respondToReceiverOffer({required bool accept}) =>
    RustLib.instance.api.crateApiReceiverRespondToReceiverOffer(accept: accept);

Future<void> cancelReceiverTransfer() =>
    RustLib.instance.api.crateApiReceiverCancelReceiverTransfer();

/// Write received inline text to a `.txt` in the receiver's download folder
/// (the same root file transfers land in) and return the saved path.  Powers
/// the offer card's "Save as .txt" action — the text never went through the
/// blob pipeline, so the receiver writes it locally on demand.
Future<String> saveTextFile({
  required String suggestedName,
  required String contents,
}) => RustLib.instance.api.crateApiReceiverSaveTextFile(
  suggestedName: suggestedName,
  contents: contents,
);

class QrPairingInfoData {
  final String ticket;
  final List<String> lanIps;

  const QrPairingInfoData({required this.ticket, required this.lanIps});

  @override
  int get hashCode => ticket.hashCode ^ lanIps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrPairingInfoData &&
          runtimeType == other.runtimeType &&
          ticket == other.ticket &&
          lanIps == other.lanIps;
}

class ReceiverConnectionPath {
  final String kind;
  final String? relayUrl;
  final String? directAddr;

  const ReceiverConnectionPath({
    required this.kind,
    this.relayUrl,
    this.directAddr,
  });

  @override
  int get hashCode => kind.hashCode ^ relayUrl.hashCode ^ directAddr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiverConnectionPath &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          relayUrl == other.relayUrl &&
          directAddr == other.directAddr;
}

class ReceiverPairingState {
  final String? code;
  final String? expiresAt;

  /// `true` when the rendezvous server has told us the code is no longer
  /// claimable (likely a sender has already consumed it) but background
  /// re-registration is currently failing.  Dart UI should keep the code
  /// visible but prompt the user to tap Refresh.
  final bool stale;

  const ReceiverPairingState({this.code, this.expiresAt, required this.stale});

  @override
  int get hashCode => code.hashCode ^ expiresAt.hashCode ^ stale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiverPairingState &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          expiresAt == other.expiresAt &&
          stale == other.stale;
}

class ReceiverRegistration {
  final String code;
  final String expiresAt;

  const ReceiverRegistration({required this.code, required this.expiresAt});

  @override
  int get hashCode => code.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiverRegistration &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          expiresAt == other.expiresAt;
}

class ReceiverTransferEvent {
  final ReceiverTransferPhase phase;
  final String senderName;
  final String senderDeviceType;
  final String destinationLabel;
  final String saveRootLabel;
  final String statusMessage;
  final BigInt itemCount;
  final BigInt totalSizeBytes;
  final BigInt bytesReceived;
  final TransferPlanData? plan;
  final TransferSnapshotData? snapshot;
  final String totalSizeLabel;
  final List<ReceiverTransferFile> files;

  /// Inline text for a text-only offer (no files).  The UI renders it with
  /// Copy / Save-as-.txt actions instead of a file list.
  final String? inlineText;
  final ReceiverConnectionPath? connectionPath;
  final String? senderEndpointId;
  final String? senderTicket;
  final UserFacingErrorData? error;

  const ReceiverTransferEvent({
    required this.phase,
    required this.senderName,
    required this.senderDeviceType,
    required this.destinationLabel,
    required this.saveRootLabel,
    required this.statusMessage,
    required this.itemCount,
    required this.totalSizeBytes,
    required this.bytesReceived,
    this.plan,
    this.snapshot,
    required this.totalSizeLabel,
    required this.files,
    this.inlineText,
    this.connectionPath,
    this.senderEndpointId,
    this.senderTicket,
    this.error,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      senderName.hashCode ^
      senderDeviceType.hashCode ^
      destinationLabel.hashCode ^
      saveRootLabel.hashCode ^
      statusMessage.hashCode ^
      itemCount.hashCode ^
      totalSizeBytes.hashCode ^
      bytesReceived.hashCode ^
      plan.hashCode ^
      snapshot.hashCode ^
      totalSizeLabel.hashCode ^
      files.hashCode ^
      inlineText.hashCode ^
      connectionPath.hashCode ^
      senderEndpointId.hashCode ^
      senderTicket.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiverTransferEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          senderName == other.senderName &&
          senderDeviceType == other.senderDeviceType &&
          destinationLabel == other.destinationLabel &&
          saveRootLabel == other.saveRootLabel &&
          statusMessage == other.statusMessage &&
          itemCount == other.itemCount &&
          totalSizeBytes == other.totalSizeBytes &&
          bytesReceived == other.bytesReceived &&
          plan == other.plan &&
          snapshot == other.snapshot &&
          totalSizeLabel == other.totalSizeLabel &&
          files == other.files &&
          inlineText == other.inlineText &&
          connectionPath == other.connectionPath &&
          senderEndpointId == other.senderEndpointId &&
          senderTicket == other.senderTicket &&
          error == other.error;
}

class ReceiverTransferFile {
  final String path;
  final BigInt size;

  const ReceiverTransferFile({required this.path, required this.size});

  @override
  int get hashCode => path.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiverTransferFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          size == other.size;
}

enum ReceiverTransferPhase {
  connecting,
  offerReady,
  receiving,
  completed,
  cancelled,
  failed,
  declined,
}
