// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'transfer.dart';

// These functions are ignored because they are not marked as `pub`: `cancel_send_session`, `fallback_destination_label`, `format_code_label`, `map_connection_candidate`, `map_connection_path`, `map_event`, `map_phase`, `map_plan_file`, `map_plan`, `map_snapshot`, `terminal_event_for_app_error`, `terminal_internal_failure_event`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Stream<SendTransferEvent> startSendTransfer({
  required SendTransferRequest request,
}) => RustLib.instance.api.crateApiSenderStartSendTransfer(request: request);

Future<void> cancelActiveSendTransfer() =>
    RustLib.instance.api.crateApiSenderCancelActiveSendTransfer();

/// One candidate transport address iroh is attempting for the peer, surfaced
/// to Dart so the connecting screen can list every IP/relay being tried.
/// `kind` uses the same `"p2p"`/`"relay"` labels as [`SendConnectionPath`].
class SendConnectionCandidate {
  final String addr;
  final String kind;
  final bool active;

  const SendConnectionCandidate({
    required this.addr,
    required this.kind,
    required this.active,
  });

  @override
  int get hashCode => addr.hashCode ^ kind.hashCode ^ active.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendConnectionCandidate &&
          runtimeType == other.runtimeType &&
          addr == other.addr &&
          kind == other.kind &&
          active == other.active;
}

class SendConnectionPath {
  final String kind;
  final String? relayUrl;
  final String? directAddr;

  const SendConnectionPath({
    required this.kind,
    this.relayUrl,
    this.directAddr,
  });

  @override
  int get hashCode => kind.hashCode ^ relayUrl.hashCode ^ directAddr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendConnectionPath &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          relayUrl == other.relayUrl &&
          directAddr == other.directAddr;
}

class SendTransferEvent {
  final SendTransferPhase phase;
  final String destinationLabel;
  final String statusMessage;
  final BigInt itemCount;
  final BigInt totalSize;
  final BigInt bytesSent;
  final TransferPlanData? plan;
  final TransferSnapshotData? snapshot;
  final String? remoteDeviceType;
  final String? remoteEndpointId;

  /// True when the peer is a throwaway browser-receiver identity (ephemeral
  /// key). Dart skips remembering it in Recent/Saved. `None` until known.
  final bool? remoteEphemeral;

  /// Re-serialized ticket of the resolved peer address (see
  /// `wisp_app::types::SendEvent::remote_ticket`).  Surfaced to Dart so
  /// the saved-devices repo can persist a `lastTicket` for code-based
  /// sends — otherwise Recent tile shows "no cached connection info".
  final String? remoteTicket;
  final SendConnectionPath? connectionPath;

  /// Every candidate path iroh is attempting, tagged active/idle. Drives the
  /// per-candidate rows on the connecting screen. Empty outside Connecting /
  /// when iroh has no candidates yet.
  final List<SendConnectionCandidate> connectionCandidates;
  final UserFacingErrorData? error;

  const SendTransferEvent({
    required this.phase,
    required this.destinationLabel,
    required this.statusMessage,
    required this.itemCount,
    required this.totalSize,
    required this.bytesSent,
    this.plan,
    this.snapshot,
    this.remoteDeviceType,
    this.remoteEndpointId,
    this.remoteEphemeral,
    this.remoteTicket,
    this.connectionPath,
    required this.connectionCandidates,
    this.error,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      destinationLabel.hashCode ^
      statusMessage.hashCode ^
      itemCount.hashCode ^
      totalSize.hashCode ^
      bytesSent.hashCode ^
      plan.hashCode ^
      snapshot.hashCode ^
      remoteDeviceType.hashCode ^
      remoteEndpointId.hashCode ^
      remoteEphemeral.hashCode ^
      remoteTicket.hashCode ^
      connectionPath.hashCode ^
      connectionCandidates.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendTransferEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          destinationLabel == other.destinationLabel &&
          statusMessage == other.statusMessage &&
          itemCount == other.itemCount &&
          totalSize == other.totalSize &&
          bytesSent == other.bytesSent &&
          plan == other.plan &&
          snapshot == other.snapshot &&
          remoteDeviceType == other.remoteDeviceType &&
          remoteEndpointId == other.remoteEndpointId &&
          remoteEphemeral == other.remoteEphemeral &&
          remoteTicket == other.remoteTicket &&
          connectionPath == other.connectionPath &&
          connectionCandidates == other.connectionCandidates &&
          error == other.error;
}

enum SendTransferPhase {
  connecting,
  waitingForDecision,
  accepted,
  declined,
  sending,
  completed,
  cancelled,
  failed,
}

class SendTransferRequest {
  final String code;
  final List<String> paths;
  final String? serverUrl;
  final String deviceName;
  final String deviceType;
  final String? ticket;
  final String? lanDestinationLabel;

  /// Text-only send.  When set, `paths` is ignored and the text is shared
  /// inline (≤ 16 KB) or as a synthetic `.txt` for larger payloads.
  final String? inlineText;

  const SendTransferRequest({
    required this.code,
    required this.paths,
    this.serverUrl,
    required this.deviceName,
    required this.deviceType,
    this.ticket,
    this.lanDestinationLabel,
    this.inlineText,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      paths.hashCode ^
      serverUrl.hashCode ^
      deviceName.hashCode ^
      deviceType.hashCode ^
      ticket.hashCode ^
      lanDestinationLabel.hashCode ^
      inlineText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendTransferRequest &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          paths == other.paths &&
          serverUrl == other.serverUrl &&
          deviceName == other.deviceName &&
          deviceType == other.deviceType &&
          ticket == other.ticket &&
          lanDestinationLabel == other.lanDestinationLabel &&
          inlineText == other.inlineText;
}
